### ISSUE TITLE
--print-manifest does not output the bosh uuid

### ISSUE THREAD

**Issue by virtmerlin** [enaml-ops/omg-product-bundle#3]
The flag should print the EXACT same manifest that would be deployed, including the director uuid so that a pipeline can use the output w/out any transformation.   Included an dexample output with the vault plugin:

bosh@c0-run1-bosh-bastion:~$ omg-cli deploy-product --bosh-url https://10.1.0.4 --bosh-port 25555 --bosh-user admin --bosh-pass gcpblah --ssl-ignore --print-manifest vault-plugin-linux --ip 10.1.2.250-10.1.2.254 --az az1 --network vault --vm-type medium --disk-type small --stemcell-name ubuntu-trusty --stemcell-ver latest

name: vault
releases:
- name: vault
  version: 0.3.0
  url: https://bosh.io/d/github.com/cloudfoundry-community/vault-boshrelease?v=0.3.0
  sha1: bd1ae82104dcf36abf64875fc5a46e1661bf2eac
- name: consul
  version: "20"
  url: https://bosh.io/d/github.com/cloudfoundry-community/consul-boshrelease?v=20
  sha1: 9a0591c6b4d88d7d756ea933e14ddf112d05f334
stemcells:
- alias: ubuntu-trusty
  os: ubuntu-trusty
  version: latest
instance_groups:
- name: vault
  persistent_disk_type: small
  instances: 1
  vm_type: medium
  stemcell: ubuntu-trusty
  azs: [az1]
  networks: [{name: vault, static_ips: [10.1.2.250-10.1.2.254]}]
  jobs:
  - name: vault
    release: vault
    properties:
      vault:
        backend:
          use_consul: true
  - name: consul
    release: consul
    properties:
      consul:
        join_hosts:
        - 10.1.2.250-10.1.2.254
  update:
    max_in_flight: 1
update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000

**Comment by xchapter7x** [comment]
this is actually an issue with the omg-cli.
a recent commit in that repo (https://github.com/enaml-ops/omg-cli/commit/84aa905e6c26cd09e6c3f3fb8b8f519149bd3821) solves this issue. 

Please download the latest omg-cli release (https://github.com/enaml-ops/omg-cli/releases/tag/v0.0.14) which should contain the fix.
