### ISSUE TITLE
cloud foundry plugin should not hardcode deployment name "cf"

### ISSUE THREAD

**Issue by sushiandbeer** [enaml-ops/omg-product-bundle#7]
The cloud foundry product plugin hardcodes the deployment name to "cf".  This prevents users from using meaningful names like "cf-staging" or "cf-sandbox", but also prevents that same BOSH director from managing multiple CF deployments.

**Comment by zmb3** [comment]
See also #4

**Comment by anwarchk** [comment]
@sushiandbeer https://github.com/enaml-ops/omg-product-bundle/releases/tag/v1.0.6 has the changes.
