### ISSUE TITLE
Product plugin should have an option to output component versions

### ISSUE THREAD

**Issue by sushiandbeer** [enaml-ops/omg-product-bundle#8]
For automation purposes, each product plugin should have an option to output components and their versions in a format that can be parsed reliably.  The format should also include the opensource release names and exact versions and the corresponding Pivotal tile name and release version.  For example, for the Cloud Foundry product plugin, something like this:

```
pivotal-elastic-runtime: 1.7.18
cf-release: 235
diego-release: 0.1467.0
cf-mysql-release: 25
garden-linux-release: 0.342.0
```

For Pivotal tiles, a good convention may be to prepend each product name with `pivotal-`.

**Comment by zmb3** [comment]
This is addressed with the `product-meta` command.
